export const state = {
  self: null,
  workspaces: [],
  currentWsId: null,
  channels: [],
  currentChatId: null,
  messages: [],
  pins: [],
  rightDrawerTab: 'members',
  rightDrawerOpen: false,
  homeMode: false,
  messagesOldestId: null,
  noMoreMsgs: false,
  roles: [],
  wsMembers: {},
  collapsedCategories: {},
};
